In [2]:
import pandas as pd
import numpy as np
import warnings
import os

import scipy
from statsmodels.formula.api import ols

from sklearn.model_selection import train_test_split
import statsmodels.api as sm

os.chdir("E:/EBAC/Material/10 - Modelos de regresión lineal y series de tiempo")
warnings.filterwarnings("ignore")

In [3]:
advertising = pd.read_csv("Advertising.csv")
advertising

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [4]:
advertising["Intercepto"] = 1

Xadvertising = advertising[["Intercepto", "TV", "Radio", "Newspaper"]].values
Yadvertising = advertising[["Sales"]].values

X_train, X_test, Y_train, Y_test = train_test_split(Xadvertising, Yadvertising, test_size = 0.70, random_state=1)
X = X_train
Y = Y_train

In [5]:
XT_X = np.matmul(np.matrix.transpose(X), X)
XT_X

array([[6.00000000e+01, 8.87480000e+03, 1.45610000e+03, 1.81670000e+03],
       [8.87480000e+03, 1.78779612e+06, 2.22791010e+05, 2.80245780e+05],
       [1.45610000e+03, 2.22791010e+05, 4.94247500e+04, 4.94345200e+04],
       [1.81670000e+03, 2.80245780e+05, 4.94345200e+04, 8.08449700e+04]])

In [6]:
XT_X_inv = np.linalg.inv(XT_X)
XT_X_inv

array([[ 1.11811634e-01, -2.72278476e-04, -1.28139059e-03,
        -7.85186416e-04],
       [-2.72278476e-04,  2.13674959e-06, -8.27673923e-07,
        -7.82375018e-07],
       [-1.28139059e-03, -8.27673923e-07,  7.73536990e-05,
        -1.56359583e-05],
       [-7.85186416e-04, -7.82375018e-07, -1.56359583e-05,
         4.22866327e-05]])

In [7]:
XT_Y = np.matmul(np.matrix.transpose(X), Y)
XT_Y

array([[   908.2 ],
       [159705.46],
       [ 24254.1 ],
       [ 28550.38]])

In [8]:
betas = np.matmul(XT_X_inv, XT_Y)
betas

array([[ 4.56662037],
       [ 0.05155567],
       [ 0.13378883],
       [-0.00999253]])

In [9]:
# Calculo de Y's pronosticadas
Y_pred = np.matmul(X, betas)
Y_pred

array([[11.44204692],
       [13.25989772],
       [21.87977548],
       [21.13423545],
       [16.76294688],
       [20.49372128],
       [17.77381058],
       [17.84545713],
       [21.2779    ],
       [11.85480212],
       [20.90655811],
       [15.72803291],
       [ 5.99161819],
       [16.0935127 ],
       [ 9.28141479],
       [17.31822055],
       [20.57810786],
       [ 9.21329917],
       [10.11706461],
       [18.19749399],
       [12.04383355],
       [23.02182381],
       [ 7.93546112],
       [12.59445413],
       [24.96697237],
       [ 5.28096317],
       [ 7.37858647],
       [22.4480117 ],
       [11.66808567],
       [13.99137264],
       [ 6.87876818],
       [23.20430952],
       [13.73760008],
       [13.26996003],
       [ 9.99779063],
       [18.53364369],
       [12.01963054],
       [15.16332653],
       [20.37521226],
       [14.93644791],
       [19.99771866],
       [12.22076737],
       [14.72288937],
       [19.95560663],
       [17.83486113],
       [23

In [10]:
# Calculo de Residuales
Resid = Y - Y_pred
Resid

array([[ 0.15795308],
       [-1.65989772],
       [-0.07977548],
       [-0.23423545],
       [-0.76294688],
       [ 1.90627872],
       [-0.67381058],
       [ 0.15454287],
       [-1.4779    ],
       [-0.05480212],
       [ 1.69344189],
       [-0.72803291],
       [ 0.90838181],
       [ 1.8064873 ],
       [ 0.41858521],
       [-0.81822055],
       [-0.57810786],
       [ 0.48670083],
       [-0.01706461],
       [-0.49749399],
       [-1.24383355],
       [-1.62182381],
       [-0.93546112],
       [ 0.00554587],
       [ 2.03302763],
       [-0.48096317],
       [ 0.72141353],
       [ 2.2519883 ],
       [-1.26808567],
       [-0.79137264],
       [-1.27876818],
       [ 0.99569048],
       [ 0.26239992],
       [-0.06996003],
       [ 4.00220937],
       [ 0.66635631],
       [-0.01963054],
       [ 1.53667347],
       [-1.47521226],
       [ 1.46355209],
       [ 0.10228134],
       [-2.12076737],
       [ 0.57711063],
       [ 0.74439337],
       [ 0.36513887],
       [ 0

In [11]:
# Calculo de suma de residuales al cuadrado
RSS = np.matmul(np.matrix.transpose(Resid), Resid)
RSS

array([[81.05568352]])

In [12]:
#Calculo de Suma total de cuadrados
TSS = np.matmul(np.matrix.transpose(Y), Y) - len(Y)*(Y.mean()**2)
TSS

array([[1674.69933333]])

In [13]:
#Calculo de coeficiente de determinacion
R_cuad = float(1-RSS/TSS)
R_cuad

0.9515998592080525

In [14]:
#Calculo de la varianza del error
s_cuad = RSS / (len(Y) - X.shape[1])
s_cuad

array([[1.44742292]])

In [15]:
#Desviacion estandar del error
import math

s = math.sqrt(s_cuad)
s

1.2030889077518785

In [16]:
# Obtencion del valor critico de la t de Student
import scipy.stats

# Grados de libertad: n - (k+1)
grados_libertad = len(Y) - X.shape[1]
Confianza = 0.90
q = (1-Confianza) / 2
t_critico = abs(scipy.stats.t.ppf(q, df=grados_libertad))
t_critico


1.6725223030755783

In [17]:
# Vector de valores particulares para TV, Radio y Periodicos de 100, 50 y 70
f = np.array([[1], [100], [50], [70]])
f

array([[  1],
       [100],
       [ 50],
       [ 70]])

In [18]:
Margen_error = t_critico * (s * (float(np.matmul(np.matmul(np.matrix.transpose(f), XT_X_inv), f))**0.5))
Margen_error

0.6751059884200861

In [19]:
Pron_puntual = float(np.matmul(np.matrix.transpose(f), betas))
Pron_puntual

15.712152044402911

In [20]:
# Limites del intervalo de confianza
Lim_inferior = Pron_puntual - Margen_error
Lim_superior = Pron_puntual + Margen_error
print("Intervalo de confianza: (", Lim_inferior, ",", Lim_superior, ")")

Intervalo de confianza: ( 15.037046055982826 , 16.387258032823 )


# Validacion de supuestos de regresion

In [21]:
# Calculo de la asimetria en residuales
skew = float(scipy.stats.skew(Resid, bias = True))
skew

0.6664225569285065

In [22]:
mean = np.mean(Resid)
std_dev = np.std(Resid, ddof=2)
sum_of_cubes = np.sum((Resid - mean) ** 3)
n = len(Resid)
manual_skew = (n / ((n-1)*(n-2))) * (sum_of_cubes / (std_dev ** 3))

print("Skewness:", manual_skew)

Skewness: 0.666326827192046


In [23]:
# Calculo de la curtosis de residuales
kurtosis = float(scipy.stats.kurtosis(Resid, fisher = False))
kurtosis

3.9375206741253486

In [24]:
sum_of_fourth_powers = np.sum((Resid - mean) ** 4)

manual_kurtosis = ((n * (n + 1) * sum_of_fourth_powers) / ((n - 1) * (n - 2) * (n - 3) * (std_dev ** 4)) - (3 * (n - 1) ** 2) / ((n - 2) * (n - 3))+3)

print("Kurtosis:", manual_kurtosis)

Kurtosis: 3.983614754956158


In [25]:
Jarque_Bera = (len(Y)/6) * (skew ** 2 + (kurtosis - 3) **2 /4)
Jarque_Bera

6.6385527798624056

In [26]:
Nivel_confianza = 0.90
scipy.stats.chi2.ppf(Nivel_confianza, df = 2)

4.605170185988092

Los residuales no tienen distribucion normal, rechazamos H0

In [27]:
from scipy.stats import jarque_bera

stat, p = jarque_bera(Resid)
print(f"Jarque-Bera Test Statistic: {stat}, p-value: {p}")


Jarque-Bera Test Statistic: 6.6385527798624056, p-value: 0.036179001774422404


# Supuesto 2: Inexistencia de autocorrelacion entre residuales

In [49]:
y_df = pd.DataFrame(Y)
x_df = pd.DataFrame(X[:,1:4])

df = pd.concat([y_df, x_df.reindex(y_df.index)], axis = 1)
df.columns = ['Y', 'X1', 'X2', 'X3']
df

Y     X1    X2     X3
0   11.6  121.0   8.4   48.7
1   11.6   48.3  47.0    8.5
2   21.8  241.7  38.0   23.2
3   20.9  286.0  13.9    3.7
4   16.0  131.1  42.8   28.9
5   22.4  195.4  47.7   52.9
6   17.1  177.0  33.4   38.7
7   18.0  163.5  36.8    7.4
8   19.8  255.4  26.9    5.5
9   11.8   76.4  26.7   22.3
10  22.6  216.4  41.7   39.6
11  15.0  142.9  29.3   12.6
12   6.9   27.5   1.6   20.7
13  17.9  206.9   8.4   26.4
14   9.7   62.3  12.6   18.3
15  16.5  151.5  41.3   58.5
16  20.0  284.3  10.6    6.4
17   9.7   66.9  11.7   36.8
18  10.1   44.7  25.8   20.6
19  17.7  265.2   2.9   43.0
20  10.8   39.5  41.1    5.8
21  21.4  292.9  28.3   43.2
22   7.0   18.8  21.7   50.4
23  12.6   75.1  35.0   52.7
24  27.0  276.9  48.9   41.8
25   4.8    8.6   2.1    1.0
26   8.1   53.5   2.0   21.4
27  24.7  220.3  49.0    3.2
28  10.4   44.5  39.3   45.1
29  13.2  136.2  19.2   16.6
30   5.6   13.2  15.9   49.6
31  24.2  261.3  42.7   54.7
32  14.0  102.7  29.6    8.4
33  13.2  120.2  19.6   11.6
34  14.0   94.2   4.9    8.1
35  19.2  193.7  35.4   75.6
36  12.0   76.3  27.5   16.0
37  16.7  197.6   3.5    5.9
38  18.9  237.4  27.5   11.0
39  16.4  199.8   3.1   34.6
40  20.1  220.5  33.2   37.9
41  10.1  149.8   1.3   24.3
42  15.3   93.9  43.5   50.5
43  20.7  184.9  43.9    1.7
44  18.2  240.1   7.3    8.7
45  23.8  296.4  36.3  100.9
46  18.0  218.4  27.7   53.4
47  16.8  276.7   2.3   23.7
48  17.0  262.9   3.5   19.5
49  10.8   36.9  38.6   65.6
50  12.4  109.8  14.3   31.7
51   9.7   59.6  12.0   43.1
52  12.3   96.2  14.8   38.9
53   5.9   17.2   4.1   31.6
54  11.0  116.0   7.7   23.1
55  19.6  219.8  33.5   45.1
56  20.8  273.7  28.9   59.7
57   8.8   26.8  33.0   19.3
58  10.9   73.4  17.0   12.9
59  14.7   74.7  49.4   45.7

In [51]:
# Ajuste de regresion lineal multimple
model = ols('Y ~ X1 + X2 + X3', data = df).fit()

from statsmodels.stats.stattools import durbin_watson

# Prueba de Durbin-Watson
durbin_watson(model.resid)

1.8596944880514208

DW es aproximado a 2, por lo que podemos descartar la existencia de autocorrelacion entre los residuales

In [52]:
Residuals = Resid.flatten()

In [53]:
numerator = np.sum(np.diff(Residuals) ** 2)
denominator = np.sum(Residuals ** 2)
DW_statistic = numerator / denominator
print("Durbin-Watson Statistic:", DW_statistic)


Durbin-Watson Statistic: 1.8596944880514341


# Supuesto 3: Homocedasticidad (igual de varianzas)

In [31]:
ResidCuad = Resid ** 2
ResidCuad = pd.DataFrame(ResidCuad)

In [62]:
X_vars = df.iloc[:,1:]
X_vars = pd.DataFrame(X_vars)

X_sq_vars = X_vars**2
X_sq_vars = pd.DataFrame(X_sq_vars)

In [67]:
df_Aux = pd.concat([ResidCuad, X_vars.reindex(y_df.index), X_sq_vars.reindex(y_df.index)], axis = 1)
df_Aux.columns = ['Residual', 'X1', 'X2', 'X3', 'X1Cuad', 'X2Cuad', 'X3Cuad']
df_Aux

Residual     X1    X2     X3    X1Cuad   X2Cuad    X3Cuad
0    0.024949  121.0   8.4   48.7  14641.00    70.56   2371.69
1    2.755260   48.3  47.0    8.5   2332.89  2209.00     72.25
2    0.006364  241.7  38.0   23.2  58418.89  1444.00    538.24
3    0.054866  286.0  13.9    3.7  81796.00   193.21     13.69
4    0.582088  131.1  42.8   28.9  17187.21  1831.84    835.21
5    3.633899  195.4  47.7   52.9  38181.16  2275.29   2798.41
6    0.454021  177.0  33.4   38.7  31329.00  1115.56   1497.69
7    0.023883  163.5  36.8    7.4  26732.25  1354.24     54.76
8    2.184188  255.4  26.9    5.5  65229.16   723.61     30.25
9    0.003003   76.4  26.7   22.3   5836.96   712.89    497.29
10   2.867745  216.4  41.7   39.6  46828.96  1738.89   1568.16
11   0.530032  142.9  29.3   12.6  20420.41   858.49    158.76
12   0.825158   27.5   1.6   20.7    756.25     2.56    428.49
13   3.263396  206.9   8.4   26.4  42807.61    70.56    696.96
14   0.175214   62.3  12.6   18.3   3881.29   158.76    334.89
15   0.669485  151.5  41.3   58.5  22952.25  1705.69   3422.25
16   0.334209  284.3  10.6    6.4  80826.49   112.36     40.96
17   0.236878   66.9  11.7   36.8   4475.61   136.89   1354.24
18   0.000291   44.7  25.8   20.6   1998.09   665.64    424.36
19   0.247500  265.2   2.9   43.0  70331.04     8.41   1849.00
20   1.547122   39.5  41.1    5.8   1560.25  1689.21     33.64
21   2.630312  292.9  28.3   43.2  85790.41   800.89   1866.24
22   0.875088   18.8  21.7   50.4    353.44   470.89   2540.16
23   0.000031   75.1  35.0   52.7   5640.01  1225.00   2777.29
24   4.133201  276.9  48.9   41.8  76673.61  2391.21   1747.24
25   0.231326    8.6   2.1    1.0     73.96     4.41      1.00
26   0.520437   53.5   2.0   21.4   2862.25     4.00    457.96
27   5.071451  220.3  49.0    3.2  48532.09  2401.00     10.24
28   1.608041   44.5  39.3   45.1   1980.25  1544.49   2034.01
29   0.626271  136.2  19.2   16.6  18550.44   368.64    275.56
30   1.635248   13.2  15.9   49.6    174.24   252.81   2460.16
31   0.991400  261.3  42.7   54.7  68277.69  1823.29   2992.09
32   0.068854  102.7  29.6    8.4  10547.29   876.16     70.56
33   0.004894  120.2  19.6   11.6  14448.04   384.16    134.56
34  16.017680   94.2   4.9    8.1   8873.64    24.01     65.61
35   0.444031  193.7  35.4   75.6  37519.69  1253.16   5715.36
36   0.000385   76.3  27.5   16.0   5821.69   756.25    256.00
37   2.361365  197.6   3.5    5.9  39045.76    12.25     34.81
38   2.176251  237.4  27.5   11.0  56358.76   756.25    121.00
39   2.141985  199.8   3.1   34.6  39920.04     9.61   1197.16
40   0.010461  220.5  33.2   37.9  48620.25  1102.24   1436.41
41   4.497654  149.8   1.3   24.3  22440.04     1.69    590.49
42   0.333057   93.9  43.5   50.5   8817.21  1892.25   2550.25
43   0.554121  184.9  43.9    1.7  34188.01  1927.21      2.89
44   0.133326  240.1   7.3    8.7  57648.01    53.29     75.69
45   0.010814  296.4  36.3  100.9  87852.96  1317.69  10180.81
46   0.997460  218.4  27.7   53.4  47698.56   767.29   2851.56
47   4.422469  276.7   2.3   23.7  76562.89     5.29    561.69
48   1.943274  262.9   3.5   19.5  69116.41    12.25    380.25
49   0.031600   36.9  38.6   65.6   1361.61  1489.96   4303.36
50   0.331948  109.8  14.3   31.7  12056.04   204.49   1004.89
51   0.784772   59.6  12.0   43.1   3552.16   144.00   1857.61
52   1.397972   96.2  14.8   38.9   9254.44   219.04   1513.21
53   0.045733   17.2   4.1   31.6    295.84    16.81    998.56
54   0.120010  116.0   7.7   23.1  13456.00    59.29    533.61
55   0.108781  219.8  33.5   45.1  48312.04  1122.25   2034.01
56   1.316415  273.7  28.9   59.7  74911.69   835.21   3564.09
57   1.878237   26.8  33.0   19.3    718.24  1089.00    372.49
58   0.162963   73.4  17.0   12.9   5387.56   289.00    166.41
59   0.016812   74.7  49.4   45.7   5580.09  2440.36   2088.49

In [68]:
# Ajuste de regresion lineal multiple
modelAux = ols('Residual ~ X1 + X1Cuad + X2 + X2Cuad + X3 + X3Cuad', data=df_Aux).fit()
RSqAux = modelAux.rsquared
RSqAux

0.15033807190548665

In [69]:
Estadistico = len(Y) * RSqAux
Estadistico

9.0202843143292

In [36]:
Nivel_confianza = 0.90
scipy.stats.chi2.ppf(Nivel_confianza, df = 2)

4.605170185988092

Al superar el valor critico podemos rechazar H0 y podemos decir que existe evidencia de Heterocedasticidad

In [71]:
# Alternativa para la prueba de White

from statsmodels.stats.diagnostic import het_white

white_test = het_white(model.resid, model.model.exog)
print("Estadistico de prueba:", white_test[0])
print("Valor p:", white_test[1])

Estadistico de prueba: 9.678675994358183
Valor p: 0.3771188662268463


A un nivel Alfa = 5%, no podemos rechazar H0, no hay evidencia significativa de Heterocedasticidad, debido a la discrepancia de las pruebas debemos considerar probar mas a fondo.

# Supuesto 4: Inexistencia de Multicolinealidad

In [48]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

Xadvertising_DF = advertising[["Intercepto", "TV", "Radio", "Newspaper"]]

vif = pd.DataFrame()
vif["Variable"] = Xadvertising_DF.columns
vif["VIF"] = [variance_inflation_factor(Xadvertising_DF.values, i) for i in range(Xadvertising_DF.shape[1])]
print(vif)


     Variable       VIF
0  Intercepto  6.848900
1          TV  1.004611
2       Radio  1.144952
3   Newspaper  1.145187


Dado que los valores tienen un VIF menor a 5, podemos concluir que no existe multicolinealidad entre las variables